title: Dog Breed Classifier
description: Classify dog breed using deep learning
about:


  This is a Dog Breed Classifier using Deep Learning built on top of Pytorch.


  The project was build by [Nidhin Pattaniyil](https://npatta01.github.io).


  More info and the source code can he found below.


  [Blog](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/)

  [Web app](https://food-img-classifier.herokuapp.com)



code: https://github.com/npatta01/web-deep-learning-classifier

sampleImages:
  - name: Standard Poodle
    url: https://upload.wikimedia.org/wikipedia/commons/f/f8/Full_attention_%288067543690%29.jpg
  - name: Vizsla
    url: https://upload.wikimedia.org/wikipedia/commons/b/b9/Anzu.JPG
  - name: Dire Wolf (not in training data)
    url: https://vignette.wikia.nocookie.net/gameofthrones/images/5/54/Nymeria-S7.png/revision/latest?cb=20170724060059
  - name: table (not in training & not a food)
    url: https://image.shutterstock.com/image-photo/brown-light-wooden-round-dining-260nw-588358070.jpg 
